[package]
name = "main"
version = "0.1.0"
authors = ["lambdadelta"]
edition = "2018"

[dependencies]
platform = { path = "../platform" }
queue = { path = "../queue" }
world = { path = "../world" }

libloading = "0.7.0"
log = "0.4.14"
simple_logger = "1.11.0"
winit = "0.25.0"